// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Ising_pseudologlikelihood
double Ising_pseudologlikelihood(const arma::mat& Y, const arma::mat& Omega);
RcppExport SEXP _IsingPPMx_Ising_pseudologlikelihood(SEXP YSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(Ising_pseudologlikelihood(Y, Omega));
    return rcpp_result_gen;
END_RCPP
}
// node_wise_pseudo_ll
double node_wise_pseudo_ll(const arma::colvec& y_it, arma::mat Omega);
RcppExport SEXP _IsingPPMx_node_wise_pseudo_ll(SEXP y_itSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y_it(y_itSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(node_wise_pseudo_ll(y_it, Omega));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ratio_add
double log_likelihood_ratio_add(const arma::colvec& tilde_y, const arma::mat& tilde_X, const arma::colvec& tilde_beta, const double new_beta, const int add_node);
RcppExport SEXP _IsingPPMx_log_likelihood_ratio_add(SEXP tilde_ySEXP, SEXP tilde_XSEXP, SEXP tilde_betaSEXP, SEXP new_betaSEXP, SEXP add_nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type tilde_y(tilde_ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tilde_X(tilde_XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type tilde_beta(tilde_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type new_beta(new_betaSEXP);
    Rcpp::traits::input_parameter< const int >::type add_node(add_nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ratio_add(tilde_y, tilde_X, tilde_beta, new_beta, add_node));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ratio_swap
double log_likelihood_ratio_swap(const arma::colvec& tilde_y, const arma::mat& tilde_X, const arma::colvec& tilde_beta, const int& node_0_t0_1, const double& new_tilde_beta, const int& node_1_t0_0, const double& old_tilde_beta);
RcppExport SEXP _IsingPPMx_log_likelihood_ratio_swap(SEXP tilde_ySEXP, SEXP tilde_XSEXP, SEXP tilde_betaSEXP, SEXP node_0_t0_1SEXP, SEXP new_tilde_betaSEXP, SEXP node_1_t0_0SEXP, SEXP old_tilde_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type tilde_y(tilde_ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tilde_X(tilde_XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type tilde_beta(tilde_betaSEXP);
    Rcpp::traits::input_parameter< const int& >::type node_0_t0_1(node_0_t0_1SEXP);
    Rcpp::traits::input_parameter< const double& >::type new_tilde_beta(new_tilde_betaSEXP);
    Rcpp::traits::input_parameter< const int& >::type node_1_t0_0(node_1_t0_0SEXP);
    Rcpp::traits::input_parameter< const double& >::type old_tilde_beta(old_tilde_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ratio_swap(tilde_y, tilde_X, tilde_beta, node_0_t0_1, new_tilde_beta, node_1_t0_0, old_tilde_beta));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ratio_global_flip
double log_likelihood_ratio_global_flip(const arma::mat& Y, const arma::mat& Omega, const arma::uvec& pair, const arma::uvec& reg_for_pos0, const arma::uvec& reg_for_pos1, const double beta_new_pos0, const double beta_new_pos1);
RcppExport SEXP _IsingPPMx_log_likelihood_ratio_global_flip(SEXP YSEXP, SEXP OmegaSEXP, SEXP pairSEXP, SEXP reg_for_pos0SEXP, SEXP reg_for_pos1SEXP, SEXP beta_new_pos0SEXP, SEXP beta_new_pos1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair(pairSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type reg_for_pos0(reg_for_pos0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type reg_for_pos1(reg_for_pos1SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos0(beta_new_pos0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos1(beta_new_pos1SEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ratio_global_flip(Y, Omega, pair, reg_for_pos0, reg_for_pos1, beta_new_pos0, beta_new_pos1));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ratio_global_swap
double log_likelihood_ratio_global_swap(const arma::mat& Y, const arma::mat& Omega, const arma::uvec& pair01, const arma::uvec& pair23, const double beta_new_pos0, const arma::uvec& indx0, const double beta_new_pos1, const arma::uvec& indx1, const double beta_new_pos2, const arma::uvec& indx2, const double beta_new_pos3, const arma::uvec& indx3);
RcppExport SEXP _IsingPPMx_log_likelihood_ratio_global_swap(SEXP YSEXP, SEXP OmegaSEXP, SEXP pair01SEXP, SEXP pair23SEXP, SEXP beta_new_pos0SEXP, SEXP indx0SEXP, SEXP beta_new_pos1SEXP, SEXP indx1SEXP, SEXP beta_new_pos2SEXP, SEXP indx2SEXP, SEXP beta_new_pos3SEXP, SEXP indx3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair01(pair01SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pair23(pair23SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos0(beta_new_pos0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indx0(indx0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos1(beta_new_pos1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indx1(indx1SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos2(beta_new_pos2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indx2(indx2SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_new_pos3(beta_new_pos3SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indx3(indx3SEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ratio_global_swap(Y, Omega, pair01, pair23, beta_new_pos0, indx0, beta_new_pos1, indx1, beta_new_pos2, indx2, beta_new_pos3, indx3));
    return rcpp_result_gen;
END_RCPP
}
// logit_bayes
arma::mat logit_bayes(const arma::colvec& y, const arma::mat& X, const arma::colvec& b0, const arma::mat& B0, const arma::colvec& bstart, const int sample, const int burn, const int thinning);
RcppExport SEXP _IsingPPMx_logit_bayes(SEXP ySEXP, SEXP XSEXP, SEXP b0SEXP, SEXP B0SEXP, SEXP bstartSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type bstart(bstartSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    rcpp_result_gen = Rcpp::wrap(logit_bayes(y, X, b0, B0, bstart, sample, burn, thinning));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_v0
Rcpp::List qIsing_v0(const arma::mat& Y, const double var_int, const double var_coef, const double par_pi, const int sample, const int burn, const int thinning);
RcppExport SEXP _IsingPPMx_qIsing_v0(SEXP YSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP par_piSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double >::type par_pi(par_piSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_v0(Y, var_int, var_coef, par_pi, sample, burn, thinning));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_PPMx_v0
Rcpp::List qIsing_PPMx_v0(const arma::mat& Y, const arma::mat& Z, const double& var_int, const double& var_coef, const double& par_pi, const double& M, const double& sigma, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_PPMx_v0(SEXP YSEXP, SEXP ZSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP par_piSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double& >::type par_pi(par_piSEXP);
    Rcpp::traits::input_parameter< const double& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_PPMx_v0(Y, Z, var_int, var_coef, par_pi, M, sigma, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_v1
Rcpp::List qIsing_v1(const arma::mat& Y, const double var_int, const double var_coef, const double par_pi, const double c, const int sample, const int burn, const int thinning);
RcppExport SEXP _IsingPPMx_qIsing_v1(SEXP YSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP par_piSEXP, SEXP cSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double >::type par_pi(par_piSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_v1(Y, var_int, var_coef, par_pi, c, sample, burn, thinning));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_PPMx_v1
Rcpp::List qIsing_PPMx_v1(const arma::mat& Y, const arma::mat& Z, const double& var_int, const double& var_coef, const double& par_pi, const double& c, const double& M, const double& sigma, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_PPMx_v1(SEXP YSEXP, SEXP ZSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP par_piSEXP, SEXP cSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double& >::type par_pi(par_piSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_PPMx_v1(Y, Z, var_int, var_coef, par_pi, c, M, sigma, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_PPMx_v2
Rcpp::List qIsing_PPMx_v2(const arma::mat& Y, const arma::mat& Z, const double& var_int, const double& var_coef, const arma::colvec& Qx, const double& c, const double& M, const double& sigma, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_PPMx_v2(SEXP YSEXP, SEXP ZSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP QxSEXP, SEXP cSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_PPMx_v2(Y, Z, var_int, var_coef, Qx, c, M, sigma, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_PPMx_v3
Rcpp::List qIsing_PPMx_v3(const arma::mat& Y, const arma::mat& Z, const arma::colvec& Qx, const double var_int, const double var_coef, const double M, const double sigma, const int sample, const int burn, const int thinning, const int C, const bool verb);
RcppExport SEXP _IsingPPMx_qIsing_PPMx_v3(SEXP YSEXP, SEXP ZSEXP, SEXP QxSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP, SEXP verbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const bool >::type verb(verbSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_PPMx_v3(Y, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C, verb));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_v3
Rcpp::List qIsing_v3(const arma::mat& Y, const arma::colvec& Qx, const double var_int, const double var_coef, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_v3(SEXP YSEXP, SEXP QxSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_v3(Y, Qx, var_int, var_coef, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// MCMC
double MCMC(bool useA);
RcppExport SEXP _IsingPPMx_MCMC(SEXP useASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type useA(useASEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC(useA));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_PPMx_v5
Rcpp::List qIsing_PPMx_v5(const arma::mat& Y, const arma::colvec& predefined_groups, const arma::mat& Z, const arma::colvec& Qx, const double var_int, const double var_coef, const double M, const double sigma, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_PPMx_v5(SEXP YSEXP, SEXP predefined_groupsSEXP, SEXP ZSEXP, SEXP QxSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type predefined_groups(predefined_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_PPMx_v5(Y, predefined_groups, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// qIsing_v5
Rcpp::List qIsing_v5(const arma::mat& Y, const arma::colvec& Qx, const double var_int, const double var_coef, const int sample, const int burn, const int thinning, const int C);
RcppExport SEXP _IsingPPMx_qIsing_v5(SEXP YSEXP, SEXP QxSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(qIsing_v5(Y, Qx, var_int, var_coef, sample, burn, thinning, C));
    return rcpp_result_gen;
END_RCPP
}
// log_beta
double log_beta(double x1, double x2);
RcppExport SEXP _IsingPPMx_log_beta(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(log_beta(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// log_gX
double log_gX(const int n, const arma::rowvec& x, const arma::rowvec& Sx);
RcppExport SEXP _IsingPPMx_log_gX(SEXP nSEXP, SEXP xSEXP, SEXP SxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type Sx(SxSEXP);
    rcpp_result_gen = Rcpp::wrap(log_gX(n, x, Sx));
    return rcpp_result_gen;
END_RCPP
}
// empty_log_gX
double empty_log_gX(const arma::rowvec& x);
RcppExport SEXP _IsingPPMx_empty_log_gX(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(empty_log_gX(x));
    return rcpp_result_gen;
END_RCPP
}
// log_cohesion
double log_cohesion(const double nh, const double sigma);
RcppExport SEXP _IsingPPMx_log_cohesion(SEXP nhSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type nh(nhSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_cohesion(nh, sigma));
    return rcpp_result_gen;
END_RCPP
}
// empty_log_cohesion
double empty_log_cohesion(const double M, const double H, const double sigma);
RcppExport SEXP _IsingPPMx_empty_log_cohesion(SEXP MSEXP, SEXP HSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type H(HSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(empty_log_cohesion(M, H, sigma));
    return rcpp_result_gen;
END_RCPP
}
// log_choose_std
double log_choose_std(int n, int k);
RcppExport SEXP _IsingPPMx_log_choose_std(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(log_choose_std(n, k));
    return rcpp_result_gen;
END_RCPP
}
// log_gammas_mid_1
double log_gammas_mid_1(int g1, int g2, double c);
RcppExport SEXP _IsingPPMx_log_gammas_mid_1(SEXP g1SEXP, SEXP g2SEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< int >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(log_gammas_mid_1(g1, g2, c));
    return rcpp_result_gen;
END_RCPP
}
// cpp_random_pair_fixed_j
arma::uvec cpp_random_pair_fixed_j(arma::uword dim, arma::uword j);
RcppExport SEXP _IsingPPMx_cpp_random_pair_fixed_j(SEXP dimSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_random_pair_fixed_j(dim, j));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mvrnormArma1
arma::colvec cpp_mvrnormArma1(const arma::colvec& mu, const arma::mat& sigma);
RcppExport SEXP _IsingPPMx_cpp_mvrnormArma1(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mvrnormArma1(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_polyagamma_h1_truncated
arma::colvec cpp_polyagamma_h1_truncated(const arma::colvec& z, const int& trunc);
RcppExport SEXP _IsingPPMx_cpp_polyagamma_h1_truncated(SEXP zSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const int& >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_polyagamma_h1_truncated(z, trunc));
    return rcpp_result_gen;
END_RCPP
}
// cpp_polyagamma_h1_devroye
arma::colvec cpp_polyagamma_h1_devroye(const arma::colvec& z);
RcppExport SEXP _IsingPPMx_cpp_polyagamma_h1_devroye(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_polyagamma_h1_devroye(z));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample
arma::uvec cpp_sample(const arma::uvec vec, const int size, const arma::colvec prob);
RcppExport SEXP _IsingPPMx_cpp_sample(SEXP vecSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample(vec, size, prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_1
unsigned cpp_sample_1(const arma::uvec& vec, const arma::colvec& prob);
RcppExport SEXP _IsingPPMx_cpp_sample_1(SEXP vecSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_1(vec, prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_cluster_v0
void cpp_update_cluster_v0(arma::uvec& rho, arma::uvec& table, arma::mat& Sx, int& H, arma::cube& BETAS, arma::cube& GAMMAS, arma::cube& B_ext, arma::cube& G_ext, unsigned index, const arma::mat& Y, const arma::mat& Z, const double M, const double sigma, const double c_par, const int C, const double pi_par, const double var_int, const double var_coef);
RcppExport SEXP _IsingPPMx_cpp_update_cluster_v0(SEXP rhoSEXP, SEXP tableSEXP, SEXP SxSEXP, SEXP HSEXP, SEXP BETASSEXP, SEXP GAMMASSEXP, SEXP B_extSEXP, SEXP G_extSEXP, SEXP indexSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP c_parSEXP, SEXP CSEXP, SEXP pi_parSEXP, SEXP var_intSEXP, SEXP var_coefSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sx(SxSEXP);
    Rcpp::traits::input_parameter< int& >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type BETAS(BETASSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type GAMMAS(GAMMASSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type B_ext(B_extSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type G_ext(G_extSEXP);
    Rcpp::traits::input_parameter< unsigned >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type c_par(c_parSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const double >::type pi_par(pi_parSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    cpp_update_cluster_v0(rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, index, Y, Z, M, sigma, c_par, C, pi_par, var_int, var_coef);
    return R_NilValue;
END_RCPP
}
// cpp_update_cluster_v2
void cpp_update_cluster_v2(unsigned index, arma::uvec& rho, arma::uvec& table, arma::mat& Sx, int& H, arma::cube& BETAS, arma::cube& GAMMAS, arma::cube& B_ext, arma::cube& G_ext, arma::cube& Ecube, arma::cube& E_ext, arma::uvec& SN, const arma::mat& Y, const arma::mat& Z, const double M, const double sigma, const arma::colvec& Qx, const double c_par, const double var_int, const double var_coef, const int C);
RcppExport SEXP _IsingPPMx_cpp_update_cluster_v2(SEXP indexSEXP, SEXP rhoSEXP, SEXP tableSEXP, SEXP SxSEXP, SEXP HSEXP, SEXP BETASSEXP, SEXP GAMMASSEXP, SEXP B_extSEXP, SEXP G_extSEXP, SEXP EcubeSEXP, SEXP E_extSEXP, SEXP SNSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP MSEXP, SEXP sigmaSEXP, SEXP QxSEXP, SEXP c_parSEXP, SEXP var_intSEXP, SEXP var_coefSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type index(indexSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sx(SxSEXP);
    Rcpp::traits::input_parameter< int& >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type BETAS(BETASSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type GAMMAS(GAMMASSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type B_ext(B_extSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type G_ext(G_extSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Ecube(EcubeSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type E_ext(E_extSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type SN(SNSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type c_par(c_parSEXP);
    Rcpp::traits::input_parameter< const double >::type var_int(var_intSEXP);
    Rcpp::traits::input_parameter< const double >::type var_coef(var_coefSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    cpp_update_cluster_v2(index, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, Ecube, E_ext, SN, Y, Z, M, sigma, Qx, c_par, var_int, var_coef, C);
    return R_NilValue;
END_RCPP
}
// coocorence
arma::mat coocorence(const arma::mat& MCMC_clusters);
RcppExport SEXP _IsingPPMx_coocorence(SEXP MCMC_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type MCMC_clusters(MCMC_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(coocorence(MCMC_clusters));
    return rcpp_result_gen;
END_RCPP
}
// pair_to_index
arma::uword pair_to_index(arma::uword i, arma::uword j);
RcppExport SEXP _IsingPPMx_pair_to_index(SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(pair_to_index(i, j));
    return rcpp_result_gen;
END_RCPP
}
// index_to_pair
arma::uvec index_to_pair(int k);
RcppExport SEXP _IsingPPMx_index_to_pair(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(index_to_pair(k));
    return rcpp_result_gen;
END_RCPP
}
// entropy
double entropy(const arma::uvec& cl);
RcppExport SEXP _IsingPPMx_entropy(SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(entropy(cl));
    return rcpp_result_gen;
END_RCPP
}
// VI
double VI(const arma::uvec& c0, const arma::uvec& c1);
RcppExport SEXP _IsingPPMx_VI(SEXP c0SEXP, SEXP c1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type c1(c1SEXP);
    rcpp_result_gen = Rcpp::wrap(VI(c0, c1));
    return rcpp_result_gen;
END_RCPP
}
// rpg
Rcpp::NumericVector rpg(const arma::colvec z, const int trunc);
RcppExport SEXP _IsingPPMx_rpg(SEXP zSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type z(zSEXP);
    Rcpp::traits::input_parameter< const int >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg(z, trunc));
    return rcpp_result_gen;
END_RCPP
}
// rG0_v0
Rcpp::List rG0_v0(const int dim, const double sd_off_diag, const double sd_diag, const double sparsity);
RcppExport SEXP _IsingPPMx_rG0_v0(SEXP dimSEXP, SEXP sd_off_diagSEXP, SEXP sd_diagSEXP, SEXP sparsitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_off_diag(sd_off_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_diag(sd_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type sparsity(sparsitySEXP);
    rcpp_result_gen = Rcpp::wrap(rG0_v0(dim, sd_off_diag, sd_diag, sparsity));
    return rcpp_result_gen;
END_RCPP
}
// rG0_v1
Rcpp::List rG0_v1(const int dim, const double sd_off_diag, const double sd_diag, const double sparsity, const double c);
RcppExport SEXP _IsingPPMx_rG0_v1(SEXP dimSEXP, SEXP sd_off_diagSEXP, SEXP sd_diagSEXP, SEXP sparsitySEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_off_diag(sd_off_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_diag(sd_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type sparsity(sparsitySEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rG0_v1(dim, sd_off_diag, sd_diag, sparsity, c));
    return rcpp_result_gen;
END_RCPP
}
// rG0_v2
Rcpp::List rG0_v2(const int dim, const arma::colvec& Qx, const double sd_off_diag, const double sd_diag, const double c);
RcppExport SEXP _IsingPPMx_rG0_v2(SEXP dimSEXP, SEXP QxSEXP, SEXP sd_off_diagSEXP, SEXP sd_diagSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_off_diag(sd_off_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type sd_diag(sd_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rG0_v2(dim, Qx, sd_off_diag, sd_diag, c));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_idx_j
int cpp_find_idx_j(const arma::uvec& v, int j);
RcppExport SEXP _IsingPPMx_cpp_find_idx_j(SEXP vSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_idx_j(v, j));
    return rcpp_result_gen;
END_RCPP
}
// w_rG0_v3
Rcpp::List w_rG0_v3(const int dim, const arma::colvec& Qx, double sd_offdiag, double sd_diag);
RcppExport SEXP _IsingPPMx_w_rG0_v3(SEXP dimSEXP, SEXP QxSEXP, SEXP sd_offdiagSEXP, SEXP sd_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Qx(QxSEXP);
    Rcpp::traits::input_parameter< double >::type sd_offdiag(sd_offdiagSEXP);
    Rcpp::traits::input_parameter< double >::type sd_diag(sd_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(w_rG0_v3(dim, Qx, sd_offdiag, sd_diag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IsingPPMx_Ising_pseudologlikelihood", (DL_FUNC) &_IsingPPMx_Ising_pseudologlikelihood, 2},
    {"_IsingPPMx_node_wise_pseudo_ll", (DL_FUNC) &_IsingPPMx_node_wise_pseudo_ll, 2},
    {"_IsingPPMx_log_likelihood_ratio_add", (DL_FUNC) &_IsingPPMx_log_likelihood_ratio_add, 5},
    {"_IsingPPMx_log_likelihood_ratio_swap", (DL_FUNC) &_IsingPPMx_log_likelihood_ratio_swap, 7},
    {"_IsingPPMx_log_likelihood_ratio_global_flip", (DL_FUNC) &_IsingPPMx_log_likelihood_ratio_global_flip, 7},
    {"_IsingPPMx_log_likelihood_ratio_global_swap", (DL_FUNC) &_IsingPPMx_log_likelihood_ratio_global_swap, 12},
    {"_IsingPPMx_logit_bayes", (DL_FUNC) &_IsingPPMx_logit_bayes, 8},
    {"_IsingPPMx_qIsing_v0", (DL_FUNC) &_IsingPPMx_qIsing_v0, 7},
    {"_IsingPPMx_qIsing_PPMx_v0", (DL_FUNC) &_IsingPPMx_qIsing_PPMx_v0, 11},
    {"_IsingPPMx_qIsing_v1", (DL_FUNC) &_IsingPPMx_qIsing_v1, 8},
    {"_IsingPPMx_qIsing_PPMx_v1", (DL_FUNC) &_IsingPPMx_qIsing_PPMx_v1, 12},
    {"_IsingPPMx_qIsing_PPMx_v2", (DL_FUNC) &_IsingPPMx_qIsing_PPMx_v2, 12},
    {"_IsingPPMx_qIsing_PPMx_v3", (DL_FUNC) &_IsingPPMx_qIsing_PPMx_v3, 12},
    {"_IsingPPMx_qIsing_v3", (DL_FUNC) &_IsingPPMx_qIsing_v3, 8},
    {"_IsingPPMx_MCMC", (DL_FUNC) &_IsingPPMx_MCMC, 1},
    {"_IsingPPMx_qIsing_PPMx_v5", (DL_FUNC) &_IsingPPMx_qIsing_PPMx_v5, 12},
    {"_IsingPPMx_qIsing_v5", (DL_FUNC) &_IsingPPMx_qIsing_v5, 8},
    {"_IsingPPMx_log_beta", (DL_FUNC) &_IsingPPMx_log_beta, 2},
    {"_IsingPPMx_log_gX", (DL_FUNC) &_IsingPPMx_log_gX, 3},
    {"_IsingPPMx_empty_log_gX", (DL_FUNC) &_IsingPPMx_empty_log_gX, 1},
    {"_IsingPPMx_log_cohesion", (DL_FUNC) &_IsingPPMx_log_cohesion, 2},
    {"_IsingPPMx_empty_log_cohesion", (DL_FUNC) &_IsingPPMx_empty_log_cohesion, 3},
    {"_IsingPPMx_log_choose_std", (DL_FUNC) &_IsingPPMx_log_choose_std, 2},
    {"_IsingPPMx_log_gammas_mid_1", (DL_FUNC) &_IsingPPMx_log_gammas_mid_1, 3},
    {"_IsingPPMx_cpp_random_pair_fixed_j", (DL_FUNC) &_IsingPPMx_cpp_random_pair_fixed_j, 2},
    {"_IsingPPMx_cpp_mvrnormArma1", (DL_FUNC) &_IsingPPMx_cpp_mvrnormArma1, 2},
    {"_IsingPPMx_cpp_polyagamma_h1_truncated", (DL_FUNC) &_IsingPPMx_cpp_polyagamma_h1_truncated, 2},
    {"_IsingPPMx_cpp_polyagamma_h1_devroye", (DL_FUNC) &_IsingPPMx_cpp_polyagamma_h1_devroye, 1},
    {"_IsingPPMx_cpp_sample", (DL_FUNC) &_IsingPPMx_cpp_sample, 3},
    {"_IsingPPMx_cpp_sample_1", (DL_FUNC) &_IsingPPMx_cpp_sample_1, 2},
    {"_IsingPPMx_cpp_update_cluster_v0", (DL_FUNC) &_IsingPPMx_cpp_update_cluster_v0, 18},
    {"_IsingPPMx_cpp_update_cluster_v2", (DL_FUNC) &_IsingPPMx_cpp_update_cluster_v2, 21},
    {"_IsingPPMx_coocorence", (DL_FUNC) &_IsingPPMx_coocorence, 1},
    {"_IsingPPMx_pair_to_index", (DL_FUNC) &_IsingPPMx_pair_to_index, 2},
    {"_IsingPPMx_index_to_pair", (DL_FUNC) &_IsingPPMx_index_to_pair, 1},
    {"_IsingPPMx_entropy", (DL_FUNC) &_IsingPPMx_entropy, 1},
    {"_IsingPPMx_VI", (DL_FUNC) &_IsingPPMx_VI, 2},
    {"_IsingPPMx_rpg", (DL_FUNC) &_IsingPPMx_rpg, 2},
    {"_IsingPPMx_rG0_v0", (DL_FUNC) &_IsingPPMx_rG0_v0, 4},
    {"_IsingPPMx_rG0_v1", (DL_FUNC) &_IsingPPMx_rG0_v1, 5},
    {"_IsingPPMx_rG0_v2", (DL_FUNC) &_IsingPPMx_rG0_v2, 5},
    {"_IsingPPMx_cpp_find_idx_j", (DL_FUNC) &_IsingPPMx_cpp_find_idx_j, 2},
    {"_IsingPPMx_w_rG0_v3", (DL_FUNC) &_IsingPPMx_w_rG0_v3, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_IsingPPMx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
