# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cpp_pseudo_ll_Omega <- function(Y, Omega) {
    .Call(`_IsingPPMx_cpp_pseudo_ll_Omega`, Y, Omega)
}

.cpp_pseudo_ll_alpha_beta <- function(Y, alpha, Beta) {
    .Call(`_IsingPPMx_cpp_pseudo_ll_alpha_beta`, Y, alpha, Beta)
}

Ising_pseudologlikelihood <- function(Y, Omega) {
    .Call(`_IsingPPMx_Ising_pseudologlikelihood`, Y, Omega)
}

node_wise_pseudo_ll <- function(y_it, Omega) {
    .Call(`_IsingPPMx_node_wise_pseudo_ll`, y_it, Omega)
}

log_likelihood_ratio_add <- function(tilde_y, tilde_X, tilde_beta, new_beta, add_node) {
    .Call(`_IsingPPMx_log_likelihood_ratio_add`, tilde_y, tilde_X, tilde_beta, new_beta, add_node)
}

log_likelihood_ratio_swap <- function(tilde_y, tilde_X, tilde_beta, node_0_t0_1, new_tilde_beta, node_1_t0_0, old_tilde_beta) {
    .Call(`_IsingPPMx_log_likelihood_ratio_swap`, tilde_y, tilde_X, tilde_beta, node_0_t0_1, new_tilde_beta, node_1_t0_0, old_tilde_beta)
}

log_likelihood_ratio_global_flip <- function(Y, Omega, pair, reg_for_pos0, reg_for_pos1, beta_new_pos0, beta_new_pos1) {
    .Call(`_IsingPPMx_log_likelihood_ratio_global_flip`, Y, Omega, pair, reg_for_pos0, reg_for_pos1, beta_new_pos0, beta_new_pos1)
}

log_likelihood_ratio_global_swap <- function(Y, Omega, pair01, pair23, beta_new_pos0, indx0, beta_new_pos1, indx1, beta_new_pos2, indx2, beta_new_pos3, indx3) {
    .Call(`_IsingPPMx_log_likelihood_ratio_global_swap`, Y, Omega, pair01, pair23, beta_new_pos0, indx0, beta_new_pos1, indx1, beta_new_pos2, indx2, beta_new_pos3, indx3)
}

#' Bayesian Logistic Regression via Polya-Gamma Augmentation
#'
#' Fits a Bayesian logistic regression model using the Polya-Gamma data
#' augmentation scheme of Polson, Scott, and Windle (2013). The posterior
#' of the coefficient vector \eqn{\boldsymbol{\beta}} is conjugate given the
#' augmented variables, and each MCMC iteration reduces to a Gaussian update.
#' Used internally as a building block for the node-wise coefficient updates
#' of the quasi-Ising samplers.
#'
#' @param y      Binary response vector of length \eqn{n}, with entries in
#'               \eqn{\{0, 1\}}.
#' @param X      Design matrix of dimension \eqn{n \times p}. For node-wise
#'               quasi-Ising updates, the column corresponding to the response
#'               node is replaced by a column of ones (intercept).
#' @param b0     Prior mean vector of length \eqn{p} for
#'               \eqn{\boldsymbol{\beta} \sim \mathcal{N}(\mathbf{b}_0, B_0)}.
#' @param B0     Prior covariance matrix \eqn{p \times p} for
#'               \eqn{\boldsymbol{\beta}}.
#' @param bstart Starting value for \eqn{\boldsymbol{\beta}}, a vector of
#'               length \eqn{p}.
#' @param sample Number of MCMC draws to retain after burn-in and thinning.
#' @param burn   Number of initial iterations to discard as burn-in.
#'               Default \code{0}.
#' @param thinning Thinning interval: one draw is stored every
#'               \code{thinning} iterations. Default \code{1} (no thinning).
#'
#' @return A numeric matrix of dimension \eqn{n} \eqn{\times} \eqn{p}.
#'   Row \eqn{s} contains the \eqn{s}-th posterior draw of
#'   \eqn{\boldsymbol{\beta}}.
#'
#' @details
#' The sampler runs for \code{burn + thinning * sample} total iterations.
#' At each step:
#' \enumerate{
#'   \item Compute the linear predictor \eqn{\boldsymbol{\psi} = X\boldsymbol{\beta}}.
#'   \item Draw Polya-Gamma weights \eqn{\omega_i \sim \mathrm{PG}(1, \psi_i)}.
#'   \item Update \eqn{\boldsymbol{\beta}} from the resulting Gaussian full conditional distribution.
#' }
#'
#' @references
#' Polson, N. G., Scott, J. G., and Windle, J. B. (2013).
#' Bayesian inference for logistic models using Polya-Gamma latent variables.
#' \emph{Journal of the American Statistical Association}, 108(504), 1339--1349.
#'
#' @seealso \code{\link{qIsing}}, \code{\link{qIsing_PPMx}}
#'
#' @export
logit_mcmc <- function(y, X, b0, B0, bstart, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_logit_mcmc`, y, X, b0, B0, bstart, sample, burn, thinning)
}

#' Bayesian Quasi-Ising Graphical Model (Single Population)
#'
#' Fits a single-population quasi-Ising graphical model via Metropolis-within-Gibbs
#' MCMC. The joint distribution is approximated by the pseudo-likelihood of
#' Besag (1975), which factorises into \eqn{p} independent node-wise logistic
#' regressions. Graph structure is learned through a finite-exchangeable-sequence
#' (FES) prior on the edge count
#' Paired interaction coefficients share information through bivariate Normal prior with correlation \eqn{\rho}.
#'
#' @param Y      Binary data matrix of dimension \eqn{p \times p}. Rows are
#'               observations, columns are nodes of the graph.
#' @param Qx     Probability vector of length \eqn{L+1}, where
#'               \eqn{L = p(p-1)/2}, encoding the FES prior on the number of
#'               active edges: \eqn{Q_x(k) = \Pr(K = k)} for
#'               \eqn{k = 0, \ldots, L}.
#' @param sd_int  Prior standard deviation for the node-wise intercepts
#'               \eqn{\alpha_j \sim \mathcal{N}(0, \texttt{sd\_int}^2)}.
#' @param sd_coef Prior standard deviation for the slab component of the
#'               interaction coefficients
#'               \eqn{\beta_{r,c} \mid \gamma_{r,c}=1 \sim \mathcal{N}(0, \texttt{sd\_coef}^2)}.
#' @param rho    Correlation parameter of the quasi-symmetric Normal prior on
#'               the paired coefficients \eqn{(\beta_{r,c}, \beta_{c,r})}.
#'               \eqn{\rho = 0} gives independence; \eqn{\rho \to 1} forces
#'               \eqn{\beta_{r,c} = \beta_{c,r}} a priori.
#' @param sample Number of MCMC draws to retain after burn-in and thinning.
#' @param burn   Number of initial iterations to discard as burn-in.
#'               Default \code{0}.
#' @param thinning Thinning interval. Default \code{1} (no thinning).
#'
#' @return A named \code{list} of length \code{sample}. Each element is itself
#'   a named list with four entries:
#'   \describe{
#'     \item{\code{Beta}}{Numeric \eqn{p \times p} matrix of interaction
#'       coefficients. Entry \eqn{(r,c)} is \eqn{\hat\beta_{r,c}}; the diagonal
#'       is zero.}
#'     \item{\code{alpha}}{Numeric vector of length \eqn{p} of node-wise
#'       intercepts.}
#'     \item{\code{ones}}{Integer vector of active-edge linear indices
#'       (1-based, \eqn{\subseteq \{1,\ldots,L\}}). Together with
#'       \code{zeros} it partitions the full edge set.}
#'     \item{\code{zeros}}{Integer vector of inactive-edge linear indices
#'       (1-based).}
#'   }
#'
#' @details
#' The sampler alternates two steps at each iteration:
#' \enumerate{
#'   \item \strong{Coefficient-smooting update step} (\eqn{\alpha}, \eqn{\beta}).
#'   \item \strong{Graph update} (\eqn{\Gamma}).
#'     A Global Add / Delete / Swap Metropolis step proposes a new graph from the
#'     FES prior \code{Qx} and accepts according to the quasi-likelihood ratio.
#' }
#'
#' @references
#' Besag, J. (1975). Statistical analysis of non-lattice data.
#' \emph{The Statistician}, 24(3), 179--195.
#'
#' Polson, N. G., Scott, J. G., and Windle, J. B. (2013).
#' Bayesian inference for logistic models using Polya-Gamma latent variables.
#' \emph{JASA}, 108(504), 1339--1349.
#'
#' @seealso \code{\link{bayes_logistic_regression}}, \code{\link{qIsing_PPMx_v5}}
#'
#' @export
qIsing_mcmc <- function(Y, Qx, sd_int, sd_coef, rho, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_qIsing_mcmc`, Y, Qx, sd_int, sd_coef, rho, sample, burn, thinning)
}

qIsing_mcmcaa <- function(Y, var_int, var_coef, par_pi, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_qIsing_mcmcaa`, Y, var_int, var_coef, par_pi, sample, burn, thinning)
}

qIsing_PPMx_v0 <- function(Y, Z, var_int, var_coef, par_pi, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v0`, Y, Z, var_int, var_coef, par_pi, M, sigma, sample, burn, thinning, C)
}

qIsing_v1 <- function(Y, var_int, var_coef, par_pi, c, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_qIsing_v1`, Y, var_int, var_coef, par_pi, c, sample, burn, thinning)
}

qIsing_PPMx_v1 <- function(Y, Z, var_int, var_coef, par_pi, c, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v1`, Y, Z, var_int, var_coef, par_pi, c, M, sigma, sample, burn, thinning, C)
}

qIsing_PPMx_v2 <- function(Y, Z, var_int, var_coef, Qx, c, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v2`, Y, Z, var_int, var_coef, Qx, c, M, sigma, sample, burn, thinning, C)
}

qIsing_PPMx_v3 <- function(Y, Z, Qx, var_int, var_coef, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L, verb = TRUE) {
    .Call(`_IsingPPMx_qIsing_PPMx_v3`, Y, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C, verb)
}

qIsing_v3 <- function(Y, Qx, var_int, var_coef, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_v3`, Y, Qx, var_int, var_coef, sample, burn, thinning, C)
}

MCMC <- function(useA) {
    .Call(`_IsingPPMx_MCMC`, useA)
}

qIsing_PPMx_v5 <- function(Y, predefined_groups, Z, Qx, var_int, var_coef, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v5`, Y, predefined_groups, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C)
}

qIsing_v5 <- function(Y, Qx, var_int, var_coef, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_v5`, Y, Qx, var_int, var_coef, sample, burn, thinning, C)
}

log_beta <- function(x1, x2) {
    .Call(`_IsingPPMx_log_beta`, x1, x2)
}

log_gX <- function(n, x, Sx) {
    .Call(`_IsingPPMx_log_gX`, n, x, Sx)
}

empty_log_gX <- function(x) {
    .Call(`_IsingPPMx_empty_log_gX`, x)
}

log_cohesion <- function(nh, sigma) {
    .Call(`_IsingPPMx_log_cohesion`, nh, sigma)
}

empty_log_cohesion <- function(M, H, sigma) {
    .Call(`_IsingPPMx_empty_log_cohesion`, M, H, sigma)
}

log_choose_std <- function(n, k) {
    .Call(`_IsingPPMx_log_choose_std`, n, k)
}

log_gammas_mid_1 <- function(g1, g2, c) {
    .Call(`_IsingPPMx_log_gammas_mid_1`, g1, g2, c)
}

cpp_random_pair_fixed_j <- function(dim, j) {
    .Call(`_IsingPPMx_cpp_random_pair_fixed_j`, dim, j)
}

cpp_mvrnormArma1 <- function(mu, sigma) {
    .Call(`_IsingPPMx_cpp_mvrnormArma1`, mu, sigma)
}

cpp_polyagamma_h1_truncated <- function(z, trunc) {
    .Call(`_IsingPPMx_cpp_polyagamma_h1_truncated`, z, trunc)
}

cpp_polyagamma_h1_devroye <- function(z) {
    .Call(`_IsingPPMx_cpp_polyagamma_h1_devroye`, z)
}

cpp_sample <- function(vec, size, prob) {
    .Call(`_IsingPPMx_cpp_sample`, vec, size, prob)
}

cpp_sample_1 <- function(vec, prob) {
    .Call(`_IsingPPMx_cpp_sample_1`, vec, prob)
}

cpp_update_cluster_v0 <- function(rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, index, Y, Z, M, sigma, c_par, C, pi_par, var_int, var_coef) {
    invisible(.Call(`_IsingPPMx_cpp_update_cluster_v0`, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, index, Y, Z, M, sigma, c_par, C, pi_par, var_int, var_coef))
}

cpp_update_cluster_v2 <- function(index, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, Ecube, E_ext, SN, Y, Z, M, sigma, Qx, c_par, var_int, var_coef, C) {
    invisible(.Call(`_IsingPPMx_cpp_update_cluster_v2`, index, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, Ecube, E_ext, SN, Y, Z, M, sigma, Qx, c_par, var_int, var_coef, C))
}

coocorence <- function(MCMC_clusters) {
    .Call(`_IsingPPMx_coocorence`, MCMC_clusters)
}

pair_to_index <- function(i, j) {
    .Call(`_IsingPPMx_pair_to_index`, i, j)
}

index_to_pair <- function(k) {
    .Call(`_IsingPPMx_index_to_pair`, k)
}

entropy <- function(cl) {
    .Call(`_IsingPPMx_entropy`, cl)
}

VI <- function(c0, c1) {
    .Call(`_IsingPPMx_VI`, c0, c1)
}

rpg <- function(z, trunc = 200L) {
    .Call(`_IsingPPMx_rpg`, z, trunc)
}

cpp_find_idx_j <- function(v, j) {
    .Call(`_IsingPPMx_cpp_find_idx_j`, v, j)
}

cp_default_wrapper <- function() {
    .Call(`_IsingPPMx_cp_default_wrapper`)
}

cp_empty_wrapper <- function(dim) {
    .Call(`_IsingPPMx_cp_empty_wrapper`, dim)
}

cp_prior_wrapper <- function(dim, Qx, sd_diag, sd_offdiag, rho) {
    .Call(`_IsingPPMx_cp_prior_wrapper`, dim, Qx, sd_diag, sd_offdiag, rho)
}

test_update_alpha_and_beta <- function(YY, BETA, alpha, mapping_vector, sd_offdiag, sd_diag, rho) {
    .Call(`_IsingPPMx_test_update_alpha_and_beta`, YY, BETA, alpha, mapping_vector, sd_offdiag, sd_diag, rho)
}

