# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ising_pseudologlikelihood <- function(Y, Omega) {
    .Call(`_IsingPPMx_Ising_pseudologlikelihood`, Y, Omega)
}

node_wise_pseudo_ll <- function(y_it, Omega) {
    .Call(`_IsingPPMx_node_wise_pseudo_ll`, y_it, Omega)
}

log_likelihood_ratio_add <- function(tilde_y, tilde_X, tilde_beta, new_beta, add_node) {
    .Call(`_IsingPPMx_log_likelihood_ratio_add`, tilde_y, tilde_X, tilde_beta, new_beta, add_node)
}

log_likelihood_ratio_swap <- function(tilde_y, tilde_X, tilde_beta, node_0_t0_1, new_tilde_beta, node_1_t0_0, old_tilde_beta) {
    .Call(`_IsingPPMx_log_likelihood_ratio_swap`, tilde_y, tilde_X, tilde_beta, node_0_t0_1, new_tilde_beta, node_1_t0_0, old_tilde_beta)
}

log_likelihood_ratio_global_flip <- function(Y, Omega, pair, reg_for_pos0, reg_for_pos1, beta_new_pos0, beta_new_pos1) {
    .Call(`_IsingPPMx_log_likelihood_ratio_global_flip`, Y, Omega, pair, reg_for_pos0, reg_for_pos1, beta_new_pos0, beta_new_pos1)
}

log_likelihood_ratio_global_swap <- function(Y, Omega, pair01, pair23, beta_new_pos0, indx0, beta_new_pos1, indx1, beta_new_pos2, indx2, beta_new_pos3, indx3) {
    .Call(`_IsingPPMx_log_likelihood_ratio_global_swap`, Y, Omega, pair01, pair23, beta_new_pos0, indx0, beta_new_pos1, indx1, beta_new_pos2, indx2, beta_new_pos3, indx3)
}

logit_bayes <- function(y, X, b0, B0, bstart, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_logit_bayes`, y, X, b0, B0, bstart, sample, burn, thinning)
}

qIsing_v0 <- function(Y, var_int, var_coef, par_pi, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_qIsing_v0`, Y, var_int, var_coef, par_pi, sample, burn, thinning)
}

qIsing_PPMx_v0 <- function(Y, Z, var_int, var_coef, par_pi, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v0`, Y, Z, var_int, var_coef, par_pi, M, sigma, sample, burn, thinning, C)
}

qIsing_v1 <- function(Y, var_int, var_coef, par_pi, c, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingPPMx_qIsing_v1`, Y, var_int, var_coef, par_pi, c, sample, burn, thinning)
}

qIsing_PPMx_v1 <- function(Y, Z, var_int, var_coef, par_pi, c, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v1`, Y, Z, var_int, var_coef, par_pi, c, M, sigma, sample, burn, thinning, C)
}

qIsing_PPMx_v2 <- function(Y, Z, var_int, var_coef, Qx, c, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v2`, Y, Z, var_int, var_coef, Qx, c, M, sigma, sample, burn, thinning, C)
}

qIsing_PPMx_v3 <- function(Y, Z, Qx, var_int, var_coef, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L, verb = TRUE) {
    .Call(`_IsingPPMx_qIsing_PPMx_v3`, Y, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C, verb)
}

qIsing_v3 <- function(Y, Qx, var_int, var_coef, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_v3`, Y, Qx, var_int, var_coef, sample, burn, thinning, C)
}

MCMC <- function(useA) {
    .Call(`_IsingPPMx_MCMC`, useA)
}

qIsing_PPMx_v5 <- function(Y, predefined_groups, Z, Qx, var_int, var_coef, M, sigma, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_PPMx_v5`, Y, predefined_groups, Z, Qx, var_int, var_coef, M, sigma, sample, burn, thinning, C)
}

qIsing_v5 <- function(Y, Qx, var_int, var_coef, sample = 1000L, burn = 0L, thinning = 1L, C = 5L) {
    .Call(`_IsingPPMx_qIsing_v5`, Y, Qx, var_int, var_coef, sample, burn, thinning, C)
}

log_beta <- function(x1, x2) {
    .Call(`_IsingPPMx_log_beta`, x1, x2)
}

log_gX <- function(n, x, Sx) {
    .Call(`_IsingPPMx_log_gX`, n, x, Sx)
}

empty_log_gX <- function(x) {
    .Call(`_IsingPPMx_empty_log_gX`, x)
}

log_cohesion <- function(nh, sigma) {
    .Call(`_IsingPPMx_log_cohesion`, nh, sigma)
}

empty_log_cohesion <- function(M, H, sigma) {
    .Call(`_IsingPPMx_empty_log_cohesion`, M, H, sigma)
}

log_choose_std <- function(n, k) {
    .Call(`_IsingPPMx_log_choose_std`, n, k)
}

log_gammas_mid_1 <- function(g1, g2, c) {
    .Call(`_IsingPPMx_log_gammas_mid_1`, g1, g2, c)
}

cpp_random_pair_fixed_j <- function(dim, j) {
    .Call(`_IsingPPMx_cpp_random_pair_fixed_j`, dim, j)
}

cpp_mvrnormArma1 <- function(mu, sigma) {
    .Call(`_IsingPPMx_cpp_mvrnormArma1`, mu, sigma)
}

cpp_polyagamma_h1_truncated <- function(z, trunc) {
    .Call(`_IsingPPMx_cpp_polyagamma_h1_truncated`, z, trunc)
}

cpp_polyagamma_h1_devroye <- function(z) {
    .Call(`_IsingPPMx_cpp_polyagamma_h1_devroye`, z)
}

cpp_sample <- function(vec, size, prob) {
    .Call(`_IsingPPMx_cpp_sample`, vec, size, prob)
}

cpp_sample_1 <- function(vec, prob) {
    .Call(`_IsingPPMx_cpp_sample_1`, vec, prob)
}

cpp_update_cluster_v0 <- function(rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, index, Y, Z, M, sigma, c_par, C, pi_par, var_int, var_coef) {
    invisible(.Call(`_IsingPPMx_cpp_update_cluster_v0`, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, index, Y, Z, M, sigma, c_par, C, pi_par, var_int, var_coef))
}

cpp_update_cluster_v2 <- function(index, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, Ecube, E_ext, SN, Y, Z, M, sigma, Qx, c_par, var_int, var_coef, C) {
    invisible(.Call(`_IsingPPMx_cpp_update_cluster_v2`, index, rho, table, Sx, H, BETAS, GAMMAS, B_ext, G_ext, Ecube, E_ext, SN, Y, Z, M, sigma, Qx, c_par, var_int, var_coef, C))
}

coocorence <- function(MCMC_clusters) {
    .Call(`_IsingPPMx_coocorence`, MCMC_clusters)
}

pair_to_index <- function(i, j) {
    .Call(`_IsingPPMx_pair_to_index`, i, j)
}

index_to_pair <- function(k) {
    .Call(`_IsingPPMx_index_to_pair`, k)
}

entropy <- function(cl) {
    .Call(`_IsingPPMx_entropy`, cl)
}

VI <- function(c0, c1) {
    .Call(`_IsingPPMx_VI`, c0, c1)
}

rpg <- function(z, trunc = 200L) {
    .Call(`_IsingPPMx_rpg`, z, trunc)
}

rG0_v0 <- function(dim, sd_off_diag, sd_diag, sparsity) {
    .Call(`_IsingPPMx_rG0_v0`, dim, sd_off_diag, sd_diag, sparsity)
}

rG0_v1 <- function(dim, sd_off_diag, sd_diag, sparsity, c) {
    .Call(`_IsingPPMx_rG0_v1`, dim, sd_off_diag, sd_diag, sparsity, c)
}

rG0_v2 <- function(dim, Qx, sd_off_diag, sd_diag, c) {
    .Call(`_IsingPPMx_rG0_v2`, dim, Qx, sd_off_diag, sd_diag, c)
}

cpp_find_idx_j <- function(v, j) {
    .Call(`_IsingPPMx_cpp_find_idx_j`, v, j)
}

w_rG0_v3 <- function(dim, Qx, sd_offdiag, sd_diag) {
    .Call(`_IsingPPMx_w_rG0_v3`, dim, Qx, sd_offdiag, sd_diag)
}

