# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

node_wise_pseudo_ll <- function(y_it, Omega) {
    .Call(`_IsingGraph_node_wise_pseudo_ll`, y_it, Omega)
}

node_wise_generalized_ll <- function(y_it, Omega, a) {
    .Call(`_IsingGraph_node_wise_generalized_ll`, y_it, Omega, a)
}

log_likelihood_ratio_flip <- function(tilde_y, tilde_X, tilde_beta, new_beta, node) {
    .Call(`_IsingGraph_log_likelihood_ratio_flip`, tilde_y, tilde_X, tilde_beta, new_beta, node)
}

log_likelihood_ratio_swap <- function(tilde_y, tilde_X, tilde_beta, new_beta, old_node_1, new_node_1) {
    .Call(`_IsingGraph_log_likelihood_ratio_swap`, tilde_y, tilde_X, tilde_beta, new_beta, old_node_1, new_node_1)
}

log_likelihood_ratio_swap_v2 <- function(tilde_y, tilde_X, tilde_beta, new_beta, old_one, new_one) {
    .Call(`_IsingGraph_log_likelihood_ratio_swap_v2`, tilde_y, tilde_X, tilde_beta, new_beta, old_one, new_one)
}

bayes_logit <- function(y, X, b0, B0, bstart, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingGraph_bayes_logit`, y, X, b0, B0, bstart, sample, burn, thinning)
}

quasi_Ising <- function(y, X, var_int, var_coef, pi_slab, sample, burn = 0L, thinning = 1L) {
    .Call(`_IsingGraph_quasi_Ising`, y, X, var_int, var_coef, pi_slab, sample, burn, thinning)
}

cpp_mvrnormArma1 <- function(mu, sigma) {
    .Call(`_IsingGraph_cpp_mvrnormArma1`, mu, sigma)
}

cpp_polyagamma_h1_truncated <- function(z, trunc) {
    .Call(`_IsingGraph_cpp_polyagamma_h1_truncated`, z, trunc)
}

cpp_polyagamma_h1_devroye <- function(z) {
    .Call(`_IsingGraph_cpp_polyagamma_h1_devroye`, z)
}

rpg <- function(z, trunc = 200L) {
    .Call(`_IsingGraph_rpg`, z, trunc)
}

w_variable_selection_step <- function(gamma, omega, p, y, X, var_int, var_coef, pi_slab) {
    .Call(`_IsingGraph_w_variable_selection_step`, gamma, omega, p, y, X, var_int, var_coef, pi_slab)
}

w_variable_selection_step_v2 <- function(gamma, omega, p, y, X, var_int, var_coef, pi_slab, beta) {
    .Call(`_IsingGraph_w_variable_selection_step_v2`, gamma, omega, p, y, X, var_int, var_coef, pi_slab, beta)
}

w_cpp_update_Omega <- function(gamma, omega, p, y, X, pi_slab, var_slab) {
    .Call(`_IsingGraph_w_cpp_update_Omega`, gamma, omega, p, y, X, pi_slab, var_slab)
}

